"""TADA's concept sets and prompts, from ``data/`` (reference code, verbatim).

``data/*.json`` is generated by ``scripts/tada/import_upstream_data.py``
from github.com/luk-st/steer-audio (MIT, Copyright (c) 2026 Lukasz
Staniszewski; licence in ``data/LICENSE.steer-audio``):

* ``steering_concepts.json``: the nine steering-benchmark concepts with
  their 50 positive/negative prompt pairs and lyrics (paper Table 8),
  CLAP and MuQ alignment queries (Table 9), and the released CAA compute
  settings and calibrated strength ranges per concept.
* ``benchmark_prompts.json``: the 100 evaluation prompts and the 20
  held-out prompts (App. G.2), with paired lyrics for vocal concepts.
* ``localization.json``: counterfactual keyword tables (Table 5), the
  per-concept patching data and similarity prompts, the patching
  settings, and the similarity prompt templates.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Tuple

DATA_DIR = Path(__file__).resolve().parent / "data"

#: The nine steering-benchmark concepts, in the reference order.
STEERING_CONCEPTS: Tuple[str, ...] = (
    "piano", "mood", "tempo", "vocal_gender", "vocal_style",
    "guitar_electronic", "violin", "rock_genre", "electronic_music",
)


@lru_cache(maxsize=None)
def load(name: str) -> dict:
    """One data file (``steering_concepts``, ``benchmark_prompts`` or
    ``localization``) as a dict."""
    return json.loads((DATA_DIR / f"{name}.json").read_text(encoding="utf-8"))


def prompt_pairs(concept: str) -> Tuple[List[str], List[str], str]:
    """``(positive, negative, lyrics)`` contrastive prompts for ``concept``."""
    c = load("steering_concepts")["concepts"][concept]
    return list(c["positive"]), list(c["negative"]), c["lyrics"]


def eval_queries(concept: str) -> Dict[str, str]:
    """``{"clap": ..., "muqt": ...}`` alignment queries for ``concept``."""
    return dict(load("steering_concepts")["eval_prompts"][concept])


def caa_eval_config(concept: str, variant: str = "loc") -> dict:
    """Released CAA evaluation settings (``loc``, ``all``, ``ablated``)."""
    return dict(load("steering_concepts")["caa_eval"][concept][variant])


def benchmark_prompts(holdout: bool = False) -> Tuple[List[str], List[str]]:
    """``(prompts, paired lyrics)``: the 100 test prompts, or the 20
    held-out prompts used for hyperparameter selection."""
    d = load("benchmark_prompts")
    if holdout:
        return list(d["holdout_prompts"]), list(d["holdout_lyrics"])
    return list(d["test_prompts"]), list(d["test_lyrics"])


def benchmark_lyrics(concept: str, holdout: bool = False) -> List[str]:
    """Lyrics per benchmark prompt as the reference eval uses them: the
    paired lyrics for vocal concepts, ``[inst]`` otherwise."""
    d = load("benchmark_prompts")
    prompts, lyrics = benchmark_prompts(holdout)
    if concept in d["vocal_concepts"]:
        return lyrics
    return ["[inst]"] * len(prompts)


def localization_concepts(model: str = "ace") -> List[str]:
    """Concepts the paper localised for ``model`` (``ace``, ``stableaudio``)."""
    return list(load("localization")["concepts_by_model"][model])


def localization_eval_prompts(concept: str, model: str = "ace") -> Dict[str, List[str]]:
    """Similarity prompts for one localisation concept: ``{"clap": [...],
    "muqt": [...]}`` before templating (see :func:`similarity_templates`)."""
    data = load("localization")["patch_data"]
    key = f"{concept}_ace" if model == "ace" and f"{concept}_ace" in data else concept
    d = data[key]
    return {"clap": list(d.get("eval_clap_prompts", [])),
            "muqt": list(d.get("eval_muqt_prompts", []))}


def similarity_templates() -> Dict[str, str]:
    """``{"clap": "This is a music of {p}", "muqt": "A {p} track"}``."""
    d = load("localization")
    return {"clap": d["clap_prompt_template"], "muqt": d["muqt_prompt_template"]}
